### ISSUE TITLE
Could not find twitter-auth.json

### ISSUE THREAD

**Issue by TrantorT** [derekoneil/twitter-feed-oke#12]
I am following Oracle's HOL, but while creating the wercker pipeline i am facing this issue:

Caused by: java.lang.NullPointerException: Could not find twitter-auth.json
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.example.SampleStreamExample.<init>(SampleStreamExample.java:53)
	at com.example.StaticTweets.<clinit>(StaticTweets.java:23)

Tests in error: 
  testGetStaticTweets(com.example.MyServiceTest): HTTP 500 Request failed.

This is a mock request right? Neverthless the twitter-auth.json is in ts place.

**Comment by derekoneil** [comment]
Hi TrantorT -- I am no longer the maintainer of this HOL... @chipbaber can you assist with this?
